#!/usr/bin/env python3
"""Prepare a docs folder from a notes directory for MkDocs."""

import argparse
import os
import re
import shutil
import textwrap
from pathlib import Path

# Directories / hidden-file patterns to skip when copying
SKIP_DIRS = {".git", ".github", "node_modules", "site", "docs"}
CODE_EXTENSIONS = {".cpp", ".c", ".h", ".hpp", ".py", ".java", ".js", ".go"}
LANG_MAP = {
    ".cpp": "cpp",
    ".c": "c",
    ".h": "c",
    ".hpp": "cpp",
    ".py": "python",
    ".java": "java",
    ".js": "javascript",
    ".go": "go",
}

# Regex matching an optional leading number prefix: one or more digits
# followed by a separator (-, _, ., or whitespace).  Used to derive a
# human-friendly page title from a filename.
_NUMBER_PREFIX_RE = re.compile(r"^\d+[-_.\s]+")

# Regex to detect existing YAML front matter (--- … ---).
_FRONT_MATTER_RE = re.compile(
    r"\A---[ \t]*\r?\n(.*?)\r?\n---[ \t]*\r?\n",
    re.DOTALL,
)


def _is_hidden(name: str) -> bool:
    """Return True for dot-prefixed names (hidden files/folders)."""
    return name.startswith(".")


def _should_skip(name: str) -> bool:
    return _is_hidden(name) or name in SKIP_DIRS


def _find_ci(directory: Path, target: str) -> Path | None:
    """Find a file in *directory* whose name matches *target* case-insensitively.

    Returns the first match (sorted for determinism) or ``None``.
    """
    low = target.lower()
    for entry in sorted(directory.iterdir()):
        if entry.is_file() and entry.name.lower() == low:
            return entry
    return None


def copy_notes(src: Path, dst: Path, exclude: set[str] | None = None) -> None:
    """Recursively copy *src* → *dst*, skipping excluded entries.

    *exclude* is an optional set of **exact** filenames to skip (only
    checked at the top level – sub-directories are copied normally).
    """
    for entry in sorted(src.iterdir()):
        if _should_skip(entry.name):
            continue
        if exclude and entry.name in exclude:
            continue
        target = dst / entry.name
        if entry.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            copy_notes(entry, target)
        else:
            shutil.copy2(entry, target)


def _title_from_filename(name: str) -> str:
    """Derive a page title from a Markdown filename.

    1. Drop the ``.md`` extension.
    2. Strip a leading number prefix (digits followed by ``-``, ``_``,
       ``.``, or whitespace).
    3. Replace underscores and hyphens with spaces.
    4. Keep original capitalisation.
    """
    stem = Path(name).stem
    stem = _NUMBER_PREFIX_RE.sub("", stem)
    return stem.replace("_", " ").replace("-", " ")


def _has_title(front_matter_body: str) -> bool:
    """Return True if the YAML front-matter block contains a ``title`` key."""
    for line in front_matter_body.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("title:") or stripped.startswith("title :"):
            return True
    return False


def _is_generated_code_page(path: Path) -> bool:
    """Return True if *path* looks like a code-page generated by
    `generate_code_pages` (e.g. ``main-cpp.md``)."""
    stem = path.stem  # e.g. "main-cpp"
    for ext_no_dot in LANG_MAP.values():
        if stem.endswith(f"-{ext_no_dot}"):
            return True
    # Also check raw extensions without the dot
    for ext in CODE_EXTENSIONS:
        tag = ext.lstrip(".")
        if stem.endswith(f"-{tag}"):
            return True
    return False


def inject_titles(docs_dir: Path) -> None:
    """Ensure every copied ``.md`` file has a ``title`` in its front matter.

    Skips:
    * The root ``index.md`` (it may come from a README promotion).
    * Generated code pages produced by `generate_code_pages`.

    If a file has no front matter at all, a new block is inserted.  If it
    has front matter but no ``title`` key, the key is added.  Files that
    already carry a ``title`` are left untouched.
    """
    for md in sorted(docs_dir.rglob("*.md")):
        # Skip root index.md
        if md.parent == docs_dir and md.name.lower() == "index.md":
            continue
        # Skip generated code pages
        if _is_generated_code_page(md):
            continue

        text = md.read_text(encoding="utf-8", errors="replace")
        title = _title_from_filename(md.name)

        m = _FRONT_MATTER_RE.match(text)
        if m:
            # Front matter exists – check for an existing title.
            if _has_title(m.group(1)):
                continue  # already has a title
            # Insert the title line at the end of the existing block.
            fm_body = m.group(1)
            rest = text[m.end():]
            new_text = f"---\n{fm_body}\ntitle: {title}\n---\n{rest}"
        else:
            # No front matter – prepend a new block.
            new_text = f"---\ntitle: {title}\n---\n{text}"

        md.write_text(new_text, encoding="utf-8")


def _fence(code: str) -> str:
    """Return a fenced code block, using a longer fence if needed."""
    fence = "```"
    while fence in code:
        fence += "`"
    return fence


def generate_code_pages(docs_dir: Path) -> None:
    """For every source-code file, create a companion .md page."""
    for path in sorted(docs_dir.rglob("*")):
        if not path.is_file():
            continue
        ext = path.suffix.lower()
        if ext not in CODE_EXTENSIONS:
            continue

        md_name = f"{path.stem}-{ext.lstrip('.')}.md"
        md_path = path.parent / md_name

        if md_path.exists():
            continue  # never overwrite an existing .md

        code = path.read_text(encoding="utf-8", errors="replace")
        lang = LANG_MAP.get(ext, "")
        fence = _fence(code)
        content = f"# {path.name}\n\n{fence}{lang}\n{code}\n{fence}\n"
        md_path.write_text(content, encoding="utf-8")


def ensure_index(notes_dir: Path, docs_dir: Path) -> set[str]:
    """Make sure *docs_dir* has an ``index.md``.

    Detection is case-insensitive:
    1. If the *notes_dir* root already contains an ``index.md`` (any case),
       it will be copied into docs normally – nothing extra to do here.
    2. Otherwise, look for a ``readme.md`` (any case) in the *notes_dir*
       root.  If found, write its contents to ``docs/index.md`` and return
       its original filename so the caller can exclude it from the copy
       (preventing a duplicate page).
    3. If neither exists, generate a small placeholder index.

    Returns a set of filenames to exclude from the top-level copy.
    """
    exclude: set[str] = set()

    # Case-insensitive check for an existing index.md in the source root.
    index_src = _find_ci(notes_dir, "index.md")
    if index_src is not None:
        # An index.md (any casing) exists – it will be copied by
        # copy_notes; nothing else to do.
        return exclude

    # No index.md – look for a readme to promote.
    readme_src = _find_ci(notes_dir, "readme.md")
    if readme_src is not None:
        content = readme_src.read_text(encoding="utf-8", errors="replace")
        (docs_dir / "index.md").write_text(content, encoding="utf-8")
        exclude.add(readme_src.name)
        return exclude

    # Fallback – generate a small placeholder.
    site_name = os.environ.get("SITE_NAME", "My Notes")
    (docs_dir / "index.md").write_text(
        f"# {site_name}\n\nWelcome to **{site_name}**.\n",
        encoding="utf-8",
    )
    return exclude


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--notes", required=True, help="Source notes directory")
    parser.add_argument("--out", required=True, help="Output build directory")
    parser.add_argument("--domain", required=True, help="Custom domain for CNAME")
    args = parser.parse_args()

    notes = Path(args.notes).resolve()
    out = Path(args.out).resolve()
    docs = out / "docs"

    # 1. Clean & recreate docs/
    if docs.exists():
        shutil.rmtree(docs)
    docs.mkdir(parents=True)

    # 2. Ensure an index.md exists (may return files to exclude from copy)
    exclude = ensure_index(notes, docs)

    # 3. Copy notes → docs (filtered)
    copy_notes(notes, docs, exclude=exclude)

    # 4. Inject page titles into copied Markdown files
    inject_titles(docs)

    # 5. Generate .md pages for source-code files
    generate_code_pages(docs)

    # 6. Write CNAME
    (docs / "CNAME").write_text(args.domain, encoding="utf-8")

    # 7. Copy mkdocs.yml template into <out>/
    template = Path(__file__).resolve().parent.parent / "mkdocs.yml"
    shutil.copy2(template, out / "mkdocs.yml")

    print(f"[OK] docs prepared in {docs}  ({sum(1 for _ in docs.rglob('*') if _.is_file())} files)")


if __name__ == "__main__":
    main()
